!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:46
!
!  Differentiation of do_cloud_convection in forward (tangent) mode:
!   variations   of useful results: co2_con
!   with respect to varying inputs: co2_con
!   RW status of diff variables: co2_con:in-out
SUBROUTINE DO_CLOUD_CONVECTION_D(am_i_root, input_opt, state_chm, &
& state_diag, state_grid, state_met, i, j, area_m2, f, ts_dyn, &
& use_diag14, diag14, use_diag38, diag38, rc, co2_con, co2_cond)
!
! !USES:
!
  USE CMN_SIZE_MOD
  USE DEPO_MERCURY_MOD, ONLY : add_hg2_snowpack
  USE DEPO_MERCURY_MOD, ONLY : add_hg2_wd
  USE DEPO_MERCURY_MOD, ONLY : add_hgp_wd
  USE ERRCODE_MOD
  USE ERROR_MOD, ONLY : it_is_nan
  USE ERROR_MOD, ONLY : it_is_finite
  USE INPUT_OPT_MOD, ONLY : optinput
  USE PHYSCONSTANTS
  USE STATE_CHM_MOD, ONLY : chmstate
  USE STATE_DIAG_MOD, ONLY : dgnstate
  USE STATE_GRID_MOD, ONLY : grdstate
  USE STATE_MET_MOD, ONLY : metstate
  USE SPECIES_MOD, ONLY : species
  USE WETSCAV_MOD, ONLY : washout
  USE WETSCAV_MOD, ONLY : ls_k_rain
  USE WETSCAV_MOD, ONLY : ls_f_prime
  IMPLICIT NONE
!
!
! !INPUT PARAMETERS:
!
! Are we on the root CPU?
  LOGICAL, INTENT(IN) :: am_i_root
! Input Options object
  TYPE(OPTINPUT), INTENT(IN) :: input_opt
! Grid State object
  TYPE(GRDSTATE), INTENT(IN) :: state_grid
! Meteorology State object
  TYPE(METSTATE), INTENT(IN) :: state_met
! Lon & lat indices
  INTEGER, INTENT(IN) :: i, j
! Surface area [m2]
  REAL(fp), INTENT(IN) :: area_m2
! Fraction of soluble species
!  for updraft scavenging
!  [unitless].  Computed by
!  routine  COMPUTE_F.
  REAL(fp), INTENT(IN) :: f(:, :)
! Dynamic timestep [sec]
  REAL(fp), INTENT(IN) :: ts_dyn
! Archive DIAG14?
  LOGICAL, INTENT(IN) :: use_diag14
! Archive DIAG38?
  LOGICAL, INTENT(IN) :: use_diag38
! Archive DIAG38?
  REAL(fp), INTENT(IN) :: co2_con
  REAL(fp), INTENT(IN) :: co2_cond
!
! !INPUT/OUTPUT PARAMETERS:
!
! Chemistry State object
  TYPE(CHMSTATE), INTENT(INOUT) :: state_chm
! Diagnostics State object
  TYPE(DGNSTATE), INTENT(INOUT) :: state_diag
!
! !OUTPUT PARAMETERS:
!
! Array for ND14 diagnostic
  REAL(fp), INTENT(OUT) :: diag14(:, :)
! Array for ND38 diagnostic
  REAL(fp), INTENT(OUT) :: diag38(:, :)
! Return code
  INTEGER, INTENT(OUT) :: rc
!
! !REMARKS:
!  Reference:
!  ============================================================================
!  Lin, SJ.  "Description of the parameterization of cumulus transport
!     in the 3D Goddard Chemistry Transport Model, NASA/GSFC, 1996.
!                                                                             .
!  Unit conversion for BMASS:
!
!      Ps - Pt (mb)| P2 - P1 | 100 Pa |  s^2  | 1  |  1 kg        kg
!     -------------+---------+--------+-------+----+--------  =  -----
!                  | Ps - Pt |   mb   | 9.8 m | Pa | m^2 s^2      m^2
!
!                                                                             .
!  NOTE: We are passing I & J down to this routine so that it can call the
!  proper code from "mercury_mod.f".  Normally, we wouldn't pass I & J as
!  arguments to columnized code.  This prevents rewriting the mercury_mod.f
!  routines ADD_Hg2_
!
! !REVISION HISTORY:
!  15 Jul 2009 - R. Yantosca - Columnized and cleaned up.
!                            - CLDMAS renamed to CMFMC and DTRN renamed
!                              to DTRAIN for consistency w/ GEOS-5.
!  17 Jul 2009 - R. Yantosca - Now do unit conversion of Q array from
!                              [kg] --> [v/v] and vice versa internally
!  14 Dec 2009 - R. Yantosca - Now remove internal unit conversion, since
!                              Q now comes in as [mol/mol] (=[v/v]) from the
!                              calling routine.
!  14 Dec 2009 - R. Yantosca - Remove COEF from the argument list
!  06 May 2010 - R. Yantosca - Now add IDENT via the argument list
!  29 Sep 2010 - R. Yantosca - Modified for MERRA met fields
!  05 Oct 2010 - R. Yantosca - Now pass COEF via the argument list
!  05 Oct 2010 - R. Yantosca - Attach ND14 and ND38 diagnostics
!  15 Oct 2010 - H. Amos     - Added BXHEIGHT and T as arguments
!  15 Oct 2010 - R. Yantosca - Added I, J, H2O2s and SO2s as arguments
!  15 Oct 2010 - H. Amos     - Added scavenging below cloud base
!  06 Apr 2011 - M.Fu, H.Amos- Bug fix: make sure washout adheres to the same
!                              algorithm as in the wet deposition code.
!  27 Jul 2011 - R. Yantosca - Declare CLDBASE as INTEGER to avoid PGI errors
!  16 Aug 2011 - J. Fisher   - Bug fix: use IS_Hg2() and IS_HgP to test if
!                              a tracer is Hg2 or HgP (for tagged species)
!  16 Aug 2011 - J. Fisher   - Now use WETLOSS instead of T0_SUM in the ND38
!                              diagnostic below the cloud.  Using T0_SUM leads
!                              us to over-count the tracer scavenged out of
!                              the column.
!  22 Oct 2012 - R. Yantosca - Now reference Headers/gigc_errcode_mod.F90
!  09 Nov 2012 - M. Payer    - Replaced all met field arrays with State_Met
!                              derived type object
!  31 May 2013 - R. Yantosca - Now pass State_Chm to WASHOUT
!  05 Sep 2013 - R. Yantosca - Bug fix: DT is apparently undefined, but still
!                              passed to WASHOUT.  Use SDT instead.  This
!                              avoids a floating-point error.
!  18 Apr 2014 - R. Yantosca - Now point to 3-D arrays internally
!  18 Apr 2014 - R. Yantosca - Now also pass N_TRACERS (to facilitate APM)
!  18 Apr 2014 - R. Yantosca - Remove code that we don't need anymore
!  04 Feb 2015 - M. Sulprizio- Fix calculation of WETLOSS for non-aerosol
!                              tracers below the cloud base (C. Friedman)
!  20 Apr 2015 - E. Lundgren - Use DELP*100/g instead of AD/area as grid box
!                              moist mass per area and remove AD from routine
!  20 May 2015 - M. Sulprizio- Apply bug fixes provided by Viral Shah:
!                              -- Remove F(K,IC) > 0 condition that prevents
!                                 archiving of deposited mass in DIAG38
!                              -- Add statement that subtracts the wet deposited
!                                 amount from the atmospheric mass
!                              -- Fix inconsistency in units when T0_SUM is used
!  04 Jun 2015 - E. Lundgren - Adapt Viral Shah bug fixes to moist mixing ratio
!  09 Jun 2015 - R. Yantosca - Now deposit Hg2, HgP to snowpack regardless of
!                              whether the dynamic ocean is used
!  15 Jun 2015 - E. Lundgren - Now use kg/kg total air as tracer units not v/v
!  22 Jun 2015 - E. Lundgren - Move QB_NUM calculation to within timestep loop
!  12 Aug 2015 - R. Yantosca - Treat MERRA2 in same way as we do for GEOS-FP
!  14 Sep 2015 - E. Lundgren - Apply bug fixes provided by Viral Shah:
!                              -- Prevent ALPHA > 1 in washout of aerosols
!                              -- Add tracer GAINED to Q before WETLOSS
!                                 calculation in aerosol washout
!  22 Apr 2016 - R. Yantosca - Now get Is_Hg2 & Is_HgP from species database
!  25 Apr 2016 - R. Yantosca - Now pass Hg category # to ADD_Hg2_* functions
!  28 Apr 2016 - R. Yantosca - Rewrite Is_Hg block to avoid unassociated
!                              pointer seg faults
!  29 Apr 2016 - R. Yantosca - Don't initialize pointers in declaration stmts
!  30 Jun 2016 - R. Yantosca - Remove instances of STT.  Now get the advected
!                              species ID from State_Chm%Map_Advect.
!  01 Jul 2016 - R. Yantosca - Now rename species DB object ThisSpc to SpcInfo
!  05 Jul 2016 - R. Yantosca - Now replace N_TRACERS argument with the
!                              State_Chm%nAdvect field
!  06 Jul 2016 - E. Lundgren - Now use kg/kg dry air as spc units, requiring
!                              use of DELP_DRY instead of DELP and PEDGE_DRY
!                              for avg mixing ratio
!  07 Jul 2016 - R. Yantosca - Bug fix: F and ISOL need to be indexed with
!                              the advected species index NA
!  07 Jul 2016 - R. Yantosca - DIAG14 and DIAG38 now are dimensioned with
!                              of size State_Chm%nWetDep instead of N_TRACERS
!  20 Sep 2016 - R. Yantosca - Rewrote IF test to avoid Gfortran compiler error
!  24 Aug 2017 - M. Sulprizio- Rename routine from DO_MERRA_CONVECTION to
!                              DO_CLOUD_CONVECTION
!  06 Nov 2017 - R. Yantosca - Bug fix: ND14 should use 1..nAdvect species
!  09 Nov 2017 - R. Yantosca - Return error condition to calling program
!EOP
!------------------------------------------------------------------------------
!BOC
!
! !DEFINED PARAMETERS:
!
! Scalars
  REAL(fp), PARAMETER :: tinynum=1e-14_fp
!
! !LOCAL VARIABLES:
!
  LOGICAL :: aer, is_hg
  INTEGER :: ic, istep, k
  INTEGER :: ktop, nc, ndt
  INTEGER :: nlay, ns, cldbase
  INTEGER :: hg_cat, na, nadvect, nw
  REAL(fp) :: cmfmc_below, alpha, alpha2
  REAL(fp) :: cmout, delq, dq
  REAL(fp) :: delqd
  REAL(fp) :: dns, entrn, qc
  REAL(fp) :: qcd
  REAL(fp) :: qc_pres, qc_scav, sdt
  REAL(fp) :: qc_presd
  REAL(fp) :: t0, t0_sum, t1
  REAL(fp) :: t1d
  REAL(fp) :: t2, t3, t4
  REAL(fp) :: t2d, t3d, t4d
  REAL(fp) :: tsum, lost, gained
  REAL(fp) :: tsumd
  REAL(fp) :: wetloss, mass_wash, mass_nowash
  REAL(fp) :: qdown, dt, f_washout
  REAL(fp) :: k_rain, washfrac, wet_hg2
  REAL(fp) :: wet_hgp, mb, qb
  REAL(fp) :: qbd
! Strings
  REAL(fp) :: qb_num, delp_dry_num
  REAL(fp) :: qb_numd
!
! Arrays
  CHARACTER(len=255) :: errmsg, thisloc
!
  REAL(fp) :: bmass(state_grid%nz)
! Pointers
  REAL(fp) :: pdown(state_grid%nz)
!
  REAL(fp), POINTER :: bxheight(:)
  REAL(fp), POINTER :: cmfmc(:)
  REAL(fp), POINTER :: dqrcu(:)
  REAL(fp), POINTER :: dtrain(:)
  REAL(fp), POINTER :: pficu(:)
  REAL(fp), POINTER :: pflcu(:)
  REAL(fp), POINTER :: reevapcn(:)
  REAL(fp), POINTER :: delp_dry(:)
  REAL(fp), POINTER :: t(:)
  REAL(fp), POINTER :: h2o2s(:)
  REAL(fp), POINTER :: so2s(:)
  REAL(fp), POINTER :: q(:, :)
  REAL(fp), POINTER :: qd(:, :)
!========================================================================
! (0)  I n i t i a l i z a t i o n
!========================================================================
! Initialize
  TYPE(SPECIES), POINTER :: spcinfo
  REAL :: gc_success
  EXTERNAL NULL
  INTEGER :: NULL
  INTRINSIC MAX
  INTRINSIC DBLE
  REAL :: g0_100
  REAL(fp) :: temp
  REAL(fp) :: temp0
!
!
  rc = gc_success
  errmsg = ''
! Point to columns of derived-type object fields
  thisloc = &
&   ' -> at Do_Merra_Convection (in module GeosCore/convection_mod.F)'
!
! Box height [m]
  bxheight => state_met%bxheight(i, j, :)
! Cloud mass flux
! [kg/m2/s]
  cmfmc => state_met%cmfmc(i, j, 2:state_grid%nz+1)
! Precip production rate:
  dqrcu => state_met%dqrcu(i, j, :)
! Detrainment flux [kg/m2/s]
  dtrain => state_met%dtrain(i, j, :)
! Evap of precip'ing conv.
  reevapcn => state_met%reevapcn(i, j, :)
! Edge dry P diff [hPa]
  delp_dry => state_met%delp_dry(i, j, :)
! Air temperature [K]
  t => state_met%t(i, j, :)
! H2O2s from sulfate_mod
  h2o2s => state_chm%h2o2afterchem(i, j, :)
! SO2s from sulfate_mod
  so2s => state_chm%so2afterchem(i, j, :)
! Chemical species
! [mol/mol dry air]
  qd => co2_cond(i, j, :, :)
  q => co2_con(i, j, :, :)
! Species database entry
! PFICU and PFLCU are on level edges
  spcinfo => NULL()
!
! Dwnwd flx of conv
!  ice precip
!  [kg/m2/s]
  pficu => state_met%pficu(i, j, 2:state_grid%nz+1)
! Dwnwd flux of conv
!  liquid precip
!  [kg/m2/s]
! # of levels and # of species
  pflcu => state_met%pflcu(i, j, 2:state_grid%nz+1)
!
  nlay = state_grid%nz
! Top level for convection
  nc = state_chm%nadvect
!
! Convection timestep [s]
  ktop = nlay - 1
!
! Internal time step for convective mixing is 300 sec.
! Doug Rotman (LLNL) says that 450 sec works just as well.
  ndt = ts_dyn
!
! Num internal timesteps (int)
  ns = ndt/300
  IF (ns .LT. 1) THEN
    ns = 1
  ELSE
    ns = ns
  END IF
! Num internal timesteps (real)
  dns = DBLE(ns)
! seconds in internal timestep
!-----------------------------------------------------------------
! Determine location of the cloud base, which is the level where
! we start to have non-zero convective precipitation formation
!-----------------------------------------------------------------
! Minimum value of cloud base is the surface level
  sdt = DBLE(ndt)/DBLE(ns)
!
!
! Find the cloud base
  cldbase = 1
!
  DO k=1,nlay
    IF (dqrcu(k) .GT. 0e+0_fp) GOTO 100
  END DO
  GOTO 110
 100 cldbase = k
!-----------------------------------------------------------------
! Compute PDOWN and BMASS
!-----------------------------------------------------------------
!
! PDOWN is the convective precipitation leaving each
! box [cm3 H2O/cm2 air/s]. This accounts for the
! contribution from both liquid & ice precip.
! PFLCU and PFICU are converted from kg/m2/s to m3/m2/s
! using water and ice densities, respectively.
! m3/m2/s becomes cm3/cm2/s using a factor of 100.
 110 DO k=1,nlay
!
! BMASS is the dry air mass per unit area for the grid box
! bounded by level K and K+1 [kg/m2]
! BMASS is equivalent to deltaP (dry) * 100 / g
! This is done to keep BMASS in the same units as CMFMC * SDT
    pdown(k) = (pflcu(k)/1000e+0_fp+pficu(k)/917e+0_fp)*100e+0_fp
!
    bmass(k) = delp_dry(k)*g0_100
  END DO
!
!-----------------------------------------------------------------
! Compute MB, the mass per unit area of dry air below the cloud
! base [kg/m2]. Calculate MB by looping over levels below the
! cloud base.
!-----------------------------------------------------------------
!
  mb = 0e+0_fp
  DO k=1,cldbase-1
    mb = mb + bmass(k)
  END DO
! Is this a Hg simulation?
!
!========================================================================
! (1)  A d v e c t e d   S p e c i e s   L o o p
!========================================================================
! Loop over only the advected species
  is_hg = input_opt%its_a_mercury_sim
!
!
! Get the species ID (modelID) from the advected species ID
  DO na=1,nc
!
! Look up the corresponding entry in the species database
    ic = state_chm%map_advect(na)
!
! Also get the corresponding wetdep ID
    spcinfo => state_chm%spcdata(ic)%info
!
! Zero the DIAG14 diagnostic array
    nw = spcinfo%wetdepid
!
!
! Zero the DIAG38 diagnostic array
    diag14(:, na) = 0.0_fp
!=====================================================================
! (2)  I n t e r n a l   T i m e   S t e p   L o o p
!=====================================================================
!
    IF (nw .GT. 0) diag38(:, nw) = 0.0_fp
!
! Initialize
    DO istep=1,ns
!
! [kg species/kg dry air]
      qc = 0e+0_fp
! [kg species/m2/timestep]
!----------------------------------------------------------
! B e l o w   C l o u d   B a s e   (K < CLDBASE)
!
! QB is the "weighted avg" mixing ratio below the cloud
! base [kg/kg dry air].
! QC is the mixing ratio of the air that moved in cumulus
! transport up to the next level [kg/kg dry air].
! MB is the dry mass of air below the cloud base per
! unit area [kg/m2] (see calculation before loop).
!-----------------------------------------------------------
! We need to make this a nested IF statement so that we don't
! get an out-of-bounds error when CLDBASE=1 (bmy, 11/18/10)
      t0_sum = 0e+0_fp
!==================================================================
! (3)  A b o v e   C l o u d   B a s e
!==================================================================
!
!
      IF (cldbase .GT. 1) THEN
!
        IF (cmfmc(cldbase-1) .GT. tinynum) THEN
!-----------------------------------------------------
! %%% Non-negligible Cloud mass flux %%%
!-----------------------------------------------------
! Calculate QB_NUM, the numerator for QB. QB is the
! weighted average mixing ratio below the cloud base.
! QB_NUM is equal to the grid box species concentrations
! [kg/kg dry air] weighted by the adjacent level pressure
! differences and summed over all levels up to just
! below the cloud base (ewl, 6/22/15)
!
!
          qb_num = 0e+0_fp
          delp_dry_num = 0e+0_fp
          qb_numd = 0.0
!
          DO k=1,cldbase-1
            qb_numd = qb_numd + delp_dry(k)*qd(k, ic)
            qb_num = qb_num + q(k, ic)*delp_dry(k)
            delp_dry_num = delp_dry_num + delp_dry(k)
          END DO
! Compute QB, the weighted avg mixing ratio below
! the cloud base [kg/kg dry air]
!
! Compute QC, the mixing ratio of the air that moved
! in cumulus transport up to the next level [kg/kg]
!
!        Dry mass of species below cloud base  +
!        Subsidence into cloud base from above
! QC =  --------------------------------------------
!            Dry air mass below cloud base
!
          qbd = qb_numd/delp_dry_num
          qb = qb_num/delp_dry_num
!
! Copy QC to all levels of the species array Q
! that are below the cloud base level [kg/kg]
          temp = mb + cmfmc(cldbase-1)*sdt
          temp0 = cmfmc(cldbase-1)*sdt
          qcd = (mb*qbd+temp0*qd(cldbase, ic))/temp
          qc = (mb*qb+temp0*q(cldbase, ic))/temp
          qd(1:cldbase-1, ic) = qcd
          q(1:cldbase-1, ic) = qc
!
        ELSE
!-----------------------------------------------------
! %%% Negligible cloud mass flux %%%
!-----------------------------------------------------
! When CMFMC is negligible, then set QC to the species
! concentration at the cloud base level [kg/kg]
!
!
          qcd = qd(cldbase, ic)
          qc = q(cldbase, ic)
!
        END IF
      ELSE
!
!-----------------------------------------------------
! If the cloud base happens at level 1, then just
! set QC to the species concentration at the surface
! level [kg/kg]
!-----------------------------------------------------
!
        qcd = qd(cldbase, ic)
        qc = q(cldbase, ic)
!
      END IF
!
! Initialize
      DO k=cldbase,ktop
!
        alpha = 0e+0_fp
        alpha2 = 0e+0_fp
        cmout = 0e+0_fp
        entrn = 0e+0_fp
        qc_pres = 0e+0_fp
! CMFMC_BELOW is the air mass [kg/m2/s] coming into the
! grid box (K) from the box immediately below (K-1).
        qc_scav = 0e+0_fp
! If we have a nonzero air mass flux coming from
! grid box (K-1) into (K) ...
!
        IF (k .EQ. 1) THEN
          cmfmc_below = 0e+0_fp
        ELSE
          cmfmc_below = cmfmc(k-1)
        END IF
!
        IF (cmfmc_below .GT. tinynum) THEN
!------------------------------------------------------------
! (3.1)  M a s s   B a l a n c e   i n   C l o u d
!
! F(K,NA) = fraction of species IC in level K that is
!           available for wet-scavenging by cloud updrafts.
!
! If ENTRN > 0 then compute the new value of QC:
!
!      species mass from below      (i.e. level K-1) +
!      species mass from this level (i.e. level K)
!  = -----------------------------------------------------
!             dry mass coming into cloud
!
! Otherwise, preserve the previous value of QC.  This will
! ensure that TERM1 - TERM2 is not a negative quantity (see
! below).
!
! Entrainment must be >= 0 (since we cannot have a negative
! flux of air into the cloud).  This condition is strong
! enough to ensure that CMOUT > 0 and will prevent floating-
! point exception.
!------------------------------------------------------------
! Air mass flowing out of cloud at grid box (K) [kg/m2/s]
!
!
! Air mass flowing into cloud at grid box (K) [kg/m2/s]
          cmout = cmfmc(k) + dtrain(k)
!
! Amount of QC preserved against scavenging [kg/kg]
          entrn = cmout - cmfmc_below
!
!                  QC_PRES = QC * ( 1e+0_fp - F(K,IC) )
!- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! Update QC taking entrainment into account [kg/kg]
! Prevent div by zero condition
          qc_presd = (1e+0_fp-f(k, na))*qcd
          qc_pres = qc*(1e+0_fp-f(k, na))
!------------------------------------------------------------
! (3.2)  M a s s   B a l a n c e   i n   L e v e l  ==> Q
!
! Terminology:
!
!  C_k-1   = cloud air mass flux from level k-1 to level k
!  C_k     = cloud air mass flux from level k   to level k+1
!  QC_k-1  = mixing ratio of species INSIDE CLOUD at level k-1
!  QC_k    = mixing ratio of species INSIDE CLOUD at level k
!  Q_k     = mixing ratio of species in level k
!  Q_k+1   = mixing ratio of species in level k+1
!
! For convenience we denote:
!
!  QC_SCAV = Amount of species wet-scavenged in updrafts
!          = QC_k-1 * F(k,IC)    [kg/kg]
!
!  QC_PRES = Amount of species preserved against
!            wet-scavenging in updrafts [kg/kg]
!          = QC_k-1 * ( 1 - F(k,IC) )
!
! Where F(k,IC) is the fraction of species IC in level k
! that is available for wet-scavenging by cloud updrafts.
! F(k,IC) is computed by routine COMPUTE_UPDRAFT_FSOL
! and passed to this routine as an argument.
!
! The cumulus transport above the cloud base is done as
! follows:
!
!                 ||///////////////////||
!                 ||//// C L O U D ////||
!                 ||                   ||
!   k+1     ^     ||         ^         ||3)   C_k * Q_k+1
!           |     ||         |         ||         |
!   --------|-----++---------|---------++---------|--------
!           |     ||         |         ||         |
!   k      C_k    ||2)   C_k * QC_k    ||         V
!                 ||                   ||
!                 ||                   ||
!           ^     ||         ^         ||4)   C_k-1 * Q_k
!           |     ||         |         ||         |
!   --------|-----++---------|---------++---------|--------
!           |     ||         |         ||         |
!   k-1   C_k-1   ||1) C_k-1 * QC_k-1  ||         V
!                 ||         * (1 - F) ||
!                 ||                   ||
!                 ||//// C L O U D ////||
!                 ||///////////////////||
!
! There are 4 terms that contribute to mass flow in
! and out of level k:
!
! 1) C_k-1 * QC_PRES = species convected from k-1 to k
! 2) C_k   * QC_k    = species convected from k   to k+1
! 3) C_k   * Q_k+1   = species subsiding from k+1 to k
! 4) C_k-1 * Q_k     = species subsiding from k   to k-1
!
! Therefore the change in species concentration is given by
!
!    DELQ = (Term 1) - (Term 2) + (Term 3) - (Term 4)
!
! and Q(K,IC) = Q(K,IC) + DELQ.
!
! The term T0 is the amount of species that is scavenged
! out of the box.
!
! Units of T0, T1, T2, T3, T4, and TSUM are
! [kg/m2/s * kg species / kg dry air]
!------------------------------------------------------------
!
!
          IF (entrn .GE. 0e+0_fp .AND. cmout .GT. 0e+0_fp) THEN
            qcd = (cmfmc_below*qc_presd+entrn*qd(k, ic))/cmout
            qc = (cmfmc_below*qc_pres+entrn*q(k, ic))/cmout
          END IF
!
!
          t1d = cmfmc_below*qc_presd
          t1 = cmfmc_below*qc_pres
          t2d = -(cmfmc(k)*qcd)
          t2 = -(cmfmc(k)*qc)
          t3d = cmfmc(k)*qd(k+1, ic)
          t3 = cmfmc(k)*q(k+1, ic)
          t4d = -(cmfmc_below*qd(k, ic))
          t4 = -(cmfmc_below*q(k, ic))
!
          tsumd = t1d + t2d + t3d + t4d
          tsum = t1 + t2 + t3 + t4
!
! change in [kg/kg]
! If DELQ > Q then do not make Q negative!!!
          delqd = sdt*tsumd/bmass(k)
          delq = sdt/bmass(k)*tsum
! Increment the species array [kg/kg]
!
          IF (q(k, ic) + delq .LT. 0) THEN
            delqd = -qd(k, ic)
            delq = -q(k, ic)
          END IF
!
! Pass T0_SUM in units of [kg species/m2/timestep].
! Converting kg dry air to kg species requires use
! of the molecular weight of air including moisture
! (ewl, 6/5/15)
          qd(k, ic) = qd(k, ic) + delqd
          q(k, ic) = q(k, ic) + delq
!
          t0_sum = t0_sum + t0*sdt
!
!
!
!
        ELSE
!------------------------------------------------------------
! (3.5)  N o   C l o u d   M a s s   F l u x   B e l o w
!------------------------------------------------------------
! If there is no cloud mass flux coming from below, set
! QC to the species concentration at this level [kg/kg]
!
!
! Bug fix for the cloud base layer, which is not necessarily
! in the boundary layer, and there could be
! "secondary convection" plumes - one in the PBL and another
! one not.  NOTE: T2 and T3 are the same terms as described
! in the above section.  (swu, 08/13/2007)
          qcd = qd(k, ic)
          qc = q(k, ic)
!
          IF (cmfmc(k) .GT. tinynum) THEN
! Species convected from K -> K+1
! [kg/m2/s * kg species/kg dry air]
!
! Species subsiding from K+1 -> K [kg/m2/s]
! [kg/m2/s * kg species/kg dry air]
            t2d = -(cmfmc(k)*qcd)
            t2 = -(cmfmc(k)*qc)
!
! Change in species concentration [kg/kg]
            t3d = cmfmc(k)*qd(k+1, ic)
            t3 = cmfmc(k)*q(k+1, ic)
!
! If DELQ > Q then do not make Q negative!!!
            delqd = sdt*(t2d+t3d)/bmass(k)
            delq = sdt/bmass(k)*(t2+t3)
! Add change in species to Q array [kg/kg]
!
            IF (q(k, ic) + delq .LT. 0.0e+0_fp) THEN
              delqd = -qd(k, ic)
              delq = -q(k, ic)
!
            END IF
!
            qd(k, ic) = qd(k, ic) + delqd
            q(k, ic) = q(k, ic) + delq
!
          END IF
        END IF
      END DO
    END DO
! End of loop over levels above cloud base
! End internal timestep loop
! Free pointer
    co2_cond = qd
    co2_con = q
    spcinfo => NULL()
  END DO
! End loop over advected species
!================================================================
! Succesful return!
!================================================================
! Nullify pointers
!
!
  NULLIFY(bxheight)
  NULLIFY(cmfmc)
  NULLIFY(dqrcu)
  NULLIFY(dtrain)
  NULLIFY(pficu)
  NULLIFY(pflcu)
  NULLIFY(reevapcn)
  NULLIFY(delp_dry)
  NULLIFY(t)
  NULLIFY(h2o2s)
  NULLIFY(so2s)
  NULLIFY(q)
! Set error code to success
!
  rc = gc_success
END SUBROUTINE DO_CLOUD_CONVECTION_D

